# Generated by Django 2.2.7 on 2019-11-19 04:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='event',
            field=models.ForeignKey(on_delete=False, to='events.Event'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assitant',
            name='assitant',
            field=models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assitant',
            name='event',
            field=models.ManyToManyField(to='events.Event'),
        ),
    ]
